package esi.oncf.vue;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrateur
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Admin = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Reinitialiser = new javax.swing.JButton();
        Retour = new javax.swing.JButton();
        JGareDepart = new javax.swing.JLabel();
        JGareArrivee = new javax.swing.JLabel();
        JDate = new javax.swing.JLabel();
        JHeure = new javax.swing.JLabel();
        JDuree = new javax.swing.JLabel();
        JTypeChaise = new javax.swing.JLabel();
        JPrix = new javax.swing.JLabel();
        GareDepart = new javax.swing.JComboBox<>();
        GareArrivee = new javax.swing.JComboBox<>();
        TypeChaise = new javax.swing.JComboBox<>();
        Duree = new javax.swing.JTextField();
        Prix = new javax.swing.JTextField();
        Heure = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        JNbrePlace = new javax.swing.JLabel();
        NbrePlace = new javax.swing.JTextField();
        JIdPlace = new javax.swing.JLabel();
        IdPlace = new javax.swing.JTextField();
        Admin1 = new javax.swing.JPanel();
        Add1 = new javax.swing.JButton();
        Reinitialiser1 = new javax.swing.JButton();
        Retour1 = new javax.swing.JButton();
        JGareDepart1 = new javax.swing.JLabel();
        JGareArrivee1 = new javax.swing.JLabel();
        JDate1 = new javax.swing.JLabel();
        JHeure1 = new javax.swing.JLabel();
        JDuree1 = new javax.swing.JLabel();
        JTypeChaise1 = new javax.swing.JLabel();
        JPrix1 = new javax.swing.JLabel();
        GareDepart1 = new javax.swing.JComboBox<>();
        GareArrivee1 = new javax.swing.JComboBox<>();
        TypeChaise1 = new javax.swing.JComboBox<>();
        Duree1 = new javax.swing.JTextField();
        Prix1 = new javax.swing.JTextField();
        Heure1 = new javax.swing.JTextField();
        Date1 = new javax.swing.JTextField();
        Logo1 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        JNbrePlace1 = new javax.swing.JLabel();
        NbrePlace1 = new javax.swing.JTextField();
        JIdPlace1 = new javax.swing.JLabel();
        IdPlace1 = new javax.swing.JTextField();
        Admin2 = new javax.swing.JPanel();
        Add2 = new javax.swing.JButton();
        Reinitialiser2 = new javax.swing.JButton();
        Retour2 = new javax.swing.JButton();
        JGareDepart2 = new javax.swing.JLabel();
        JGareArrivee2 = new javax.swing.JLabel();
        JDate2 = new javax.swing.JLabel();
        JHeure2 = new javax.swing.JLabel();
        JDuree2 = new javax.swing.JLabel();
        JTypeChaise2 = new javax.swing.JLabel();
        JPrix2 = new javax.swing.JLabel();
        GareDepart2 = new javax.swing.JComboBox<>();
        GareArrivee2 = new javax.swing.JComboBox<>();
        TypeChaise2 = new javax.swing.JComboBox<>();
        Duree2 = new javax.swing.JTextField();
        Prix2 = new javax.swing.JTextField();
        Heure2 = new javax.swing.JTextField();
        Date2 = new javax.swing.JTextField();
        Logo2 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        JNbrePlace2 = new javax.swing.JLabel();
        NbrePlace2 = new javax.swing.JTextField();
        JIdPlace2 = new javax.swing.JLabel();
        IdPlace2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Logo3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        button2 = new java.awt.Button();
        button1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();

        Admin.setBackground(new java.awt.Color(255, 125, 16));

        Add.setBackground(new java.awt.Color(0, 255, 51));
        Add.setText("Ajouter");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Reinitialiser.setBackground(new java.awt.Color(255, 0, 0));
        Reinitialiser.setText("Reinitialiser");
        Reinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReinitialiserActionPerformed(evt);
            }
        });

        Retour.setText("< Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        JGareDepart.setText("Gare de Départ");

        JGareArrivee.setText("Gare d'Arrivée");

        JDate.setText("Date de voyage");

        JHeure.setText("Heure de départ");

        JDuree.setText("Durée de voyage");

        JTypeChaise.setText("Type de chaise");

        JPrix.setText("Prix ");

        GareDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rabat", "Oujda", "Marrakech", "Fès", "Meknès", "Kénitra", "Casablanca", "Tanger", "Nador", "Oued Zem", "El Jadida", "Safi", "Sidi Kacem" }));
        GareDepart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GareDepartItemStateChanged(evt);
            }
        });
        GareDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GareDepartActionPerformed(evt);
            }
        });

        GareArrivee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oujda", "Marrakech", "Fès", "Meknès", "Kénitra", "Rabat", "Casablanca", "Tanger", "Nador", "Oued Zem", "El Jadida", "Safi", "Sidi Kacem" }));

        TypeChaise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ere Classe", "2eme Classe" }));

        Duree.setText("hh:mm");

        Prix.setText("Saisir le prix");
        Prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrixActionPerformed(evt);
            }
        });

        Heure.setText("hh:mm");

        Date.setText("dd/mm/yyyy");

        Logo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma/ac/esi/image/oncf.png"))); // NOI18N

        Title.setFont(new java.awt.Font("MS Gothic", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("ADD TRAIN");
        Title.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        Title.setMaximumSize(new java.awt.Dimension(200, 100));
        Title.setMinimumSize(new java.awt.Dimension(100, 50));

        JNbrePlace.setText("Nombre de place");

        NbrePlace.setText("123...");
        NbrePlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbrePlaceActionPerformed(evt);
            }
        });

        JIdPlace.setText("ID des places");

        IdPlace.setText("(debut)..-..(fin)");
        IdPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPlaceActionPerformed(evt);
            }
        });

        Admin1.setBackground(new java.awt.Color(255, 125, 16));

        Add1.setBackground(new java.awt.Color(0, 255, 51));
        Add1.setText("Ajouter");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });

        Reinitialiser1.setBackground(new java.awt.Color(255, 0, 0));
        Reinitialiser1.setText("Reinitialiser");
        Reinitialiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reinitialiser1ActionPerformed(evt);
            }
        });

        Retour1.setText("< Retour");
        Retour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour1ActionPerformed(evt);
            }
        });

        JGareDepart1.setText("Gare de Départ");

        JGareArrivee1.setText("Gare d'Arrivée");

        JDate1.setText("Date de voyage");

        JHeure1.setText("Heure de départ");

        JDuree1.setText("Durée de voyage");

        JTypeChaise1.setText("Type de chaise");

        JPrix1.setText("Prix ");

        GareDepart1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rabat", "Oujda", "Marrakech", "Fès", "Meknès", "Kénitra", "Casablanca", "Tanger", "Nador", "Oued Zem", "El Jadida", "Safi", "Sidi Kacem" }));
        GareDepart1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GareDepart1ItemStateChanged(evt);
            }
        });
        GareDepart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GareDepart1ActionPerformed(evt);
            }
        });

        GareArrivee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oujda", "Marrakech", "Fès", "Meknès", "Kénitra", "Rabat", "Casablanca", "Tanger", "Nador", "Oued Zem", "El Jadida", "Safi", "Sidi Kacem" }));

        TypeChaise1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ere Classe", "2eme Classe" }));

        Duree1.setText("hh:mm");

        Prix1.setText("Saisir le prix");
        Prix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prix1ActionPerformed(evt);
            }
        });

        Heure1.setText("hh:mm");

        Date1.setText("dd/mm/yyyy");

        Logo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma/ac/esi/image/oncf.png"))); // NOI18N

        Title1.setFont(new java.awt.Font("MS Gothic", 0, 36)); // NOI18N
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("ADD TRAIN");
        Title1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        Title1.setMaximumSize(new java.awt.Dimension(200, 100));
        Title1.setMinimumSize(new java.awt.Dimension(100, 50));

        JNbrePlace1.setText("Nombre de place");

        NbrePlace1.setText("123...");
        NbrePlace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbrePlace1ActionPerformed(evt);
            }
        });

        JIdPlace1.setText("ID des places");

        IdPlace1.setText("(debut)..-..(fin)");
        IdPlace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPlace1ActionPerformed(evt);
            }
        });

        Admin2.setBackground(new java.awt.Color(255, 125, 16));

        Add2.setBackground(new java.awt.Color(0, 255, 51));
        Add2.setText("Ajouter");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });

        Reinitialiser2.setBackground(new java.awt.Color(255, 0, 0));
        Reinitialiser2.setText("Reinitialiser");
        Reinitialiser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reinitialiser2ActionPerformed(evt);
            }
        });

        Retour2.setText("< Retour");
        Retour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour2ActionPerformed(evt);
            }
        });

        JGareDepart2.setText("Gare de Départ");

        JGareArrivee2.setText("Gare d'Arrivée");

        JDate2.setText("Date de voyage");

        JHeure2.setText("Heure de départ");

        JDuree2.setText("Durée de voyage");

        JTypeChaise2.setText("Type de chaise");

        JPrix2.setText("Prix ");

        GareDepart2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rabat", "Oujda", "Marrakech", "Fès", "Meknès", "Kénitra", "Casablanca", "Tanger", "Nador", "Oued Zem", "El Jadida", "Safi", "Sidi Kacem" }));
        GareDepart2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GareDepart2ItemStateChanged(evt);
            }
        });
        GareDepart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GareDepart2ActionPerformed(evt);
            }
        });

        GareArrivee2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oujda", "Marrakech", "Fès", "Meknès", "Kénitra", "Rabat", "Casablanca", "Tanger", "Nador", "Oued Zem", "El Jadida", "Safi", "Sidi Kacem" }));

        TypeChaise2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ere Classe", "2eme Classe" }));

        Duree2.setText("hh:mm");

        Prix2.setText("Saisir le prix");
        Prix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prix2ActionPerformed(evt);
            }
        });

        Heure2.setText("hh:mm");

        Date2.setText("dd/mm/yyyy");

        Logo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma/ac/esi/image/oncf.png"))); // NOI18N

        Title2.setFont(new java.awt.Font("MS Gothic", 0, 36)); // NOI18N
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("ADD TRAIN");
        Title2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        Title2.setMaximumSize(new java.awt.Dimension(200, 100));
        Title2.setMinimumSize(new java.awt.Dimension(100, 50));

        JNbrePlace2.setText("Nombre de place");

        NbrePlace2.setText("123...");
        NbrePlace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbrePlace2ActionPerformed(evt);
            }
        });

        JIdPlace2.setText("ID des places");

        IdPlace2.setText("(debut)..-..(fin)");
        IdPlace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPlace2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Admin2Layout = new javax.swing.GroupLayout(Admin2);
        Admin2.setLayout(Admin2Layout);
        Admin2Layout.setHorizontalGroup(
            Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Retour2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reinitialiser2)
                        .addGap(12, 12, 12)
                        .addComponent(Add2)
                        .addGap(12, 12, 12))
                    .addGroup(Admin2Layout.createSequentialGroup()
                        .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Admin2Layout.createSequentialGroup()
                                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JGareArrivee2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JGareDepart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JHeure2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(JTypeChaise2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Prix2)
                                    .addGroup(Admin2Layout.createSequentialGroup()
                                        .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(GareArrivee2, 0, 197, Short.MAX_VALUE)
                                            .addComponent(Heure2)
                                            .addComponent(GareDepart2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Date2))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TypeChaise2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Admin2Layout.createSequentialGroup()
                                .addComponent(JDuree2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Duree2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)))
                .addGap(129, 129, 129)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNbrePlace2)
                    .addComponent(JIdPlace2))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdPlace2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbrePlace2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(Admin2Layout.createSequentialGroup()
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Admin2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(JPrix2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Admin2Layout.setVerticalGroup(
            Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Admin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JGareDepart2)
                    .addComponent(GareDepart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNbrePlace2)
                    .addComponent(NbrePlace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JGareArrivee2)
                    .addComponent(GareArrivee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JIdPlace2)
                    .addComponent(IdPlace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDate2)
                    .addComponent(Date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JHeure2)
                    .addComponent(Heure2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDuree2)
                    .addComponent(Duree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTypeChaise2)
                    .addComponent(TypeChaise2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPrix2)
                    .addComponent(Prix2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour2)
                    .addComponent(Reinitialiser2)
                    .addComponent(Add2))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout Admin1Layout = new javax.swing.GroupLayout(Admin1);
        Admin1.setLayout(Admin1Layout);
        Admin1Layout.setHorizontalGroup(
            Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Admin1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Retour1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reinitialiser1)
                        .addGap(12, 12, 12)
                        .addComponent(Add1)
                        .addGap(12, 12, 12))
                    .addGroup(Admin1Layout.createSequentialGroup()
                        .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Admin1Layout.createSequentialGroup()
                                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JGareArrivee1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JGareDepart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JHeure1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(JTypeChaise1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Prix1)
                                    .addGroup(Admin1Layout.createSequentialGroup()
                                        .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(GareArrivee1, 0, 197, Short.MAX_VALUE)
                                            .addComponent(Heure1)
                                            .addComponent(GareDepart1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Date1))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TypeChaise1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Admin1Layout.createSequentialGroup()
                                .addComponent(JDuree1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Duree1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)))
                .addGap(129, 129, 129)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNbrePlace1)
                    .addComponent(JIdPlace1))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbrePlace1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(Admin1Layout.createSequentialGroup()
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Admin1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(JPrix1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Admin1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Admin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Admin1Layout.setVerticalGroup(
            Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Admin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JGareDepart1)
                    .addComponent(GareDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNbrePlace1)
                    .addComponent(NbrePlace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JGareArrivee1)
                    .addComponent(GareArrivee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JIdPlace1)
                    .addComponent(IdPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDate1)
                    .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JHeure1)
                    .addComponent(Heure1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDuree1)
                    .addComponent(Duree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTypeChaise1)
                    .addComponent(TypeChaise1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPrix1)
                    .addComponent(Prix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour1)
                    .addComponent(Reinitialiser1)
                    .addComponent(Add1))
                .addGap(53, 53, 53))
            .addGroup(Admin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Admin1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Admin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Retour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reinitialiser)
                        .addGap(12, 12, 12)
                        .addComponent(Add)
                        .addGap(12, 12, 12))
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminLayout.createSequentialGroup()
                                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JGareArrivee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JGareDepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JHeure, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(JTypeChaise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Prix)
                                    .addGroup(AdminLayout.createSequentialGroup()
                                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(GareArrivee, 0, 197, Short.MAX_VALUE)
                                            .addComponent(Heure)
                                            .addComponent(GareDepart, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Date))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TypeChaise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(AdminLayout.createSequentialGroup()
                                .addComponent(JDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Duree, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)))
                .addGap(129, 129, 129)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNbrePlace)
                    .addComponent(JIdPlace))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbrePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(AdminLayout.createSequentialGroup()
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(JPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Admin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JGareDepart)
                    .addComponent(GareDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNbrePlace)
                    .addComponent(NbrePlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JGareArrivee)
                    .addComponent(GareArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JIdPlace)
                    .addComponent(IdPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDate)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JHeure)
                    .addComponent(Heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDuree)
                    .addComponent(Duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTypeChaise)
                    .addComponent(TypeChaise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPrix)
                    .addComponent(Prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour)
                    .addComponent(Reinitialiser)
                    .addComponent(Add))
                .addGap(53, 53, 53))
            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Admin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hhh");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 153, 51));

        jPanel2.setBackground(new java.awt.Color(255, 125, 16));

        Logo3.setBackground(new java.awt.Color(255, 153, 51));
        Logo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma/ac/esi/image/oncf.png"))); // NOI18N

        jLabel6.setText("Voyageurs");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jTextField2.setText("HH/mm/ss");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Type de chaise");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rabat ", "Casablanca", "Marrakech", "Oujda", "Tanger" }));

        jTextField1.setText("dd/mm/yyyy");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gare de Départ");

        jLabel2.setText("Date de voyage");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ère classe", "2ème classe", " " }));

        jLabel3.setText("Gare d'Arrivée");

        jLabel4.setText("Heure de voyage");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rabat", "Marrakech", "Casablanca", "Oued Zem", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        button2.setLabel("Réinitialiser");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button1.setLabel("Réserver");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jButton1.setText("Réserver par carte de réduction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(56, 56, 56))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void ReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReinitialiserActionPerformed
        // Réinitialiser tous les JComboBox à leur premier élément
        GareDepart.setSelectedIndex(0);
        GareArrivee.setSelectedIndex(0);
        TypeChaise.setSelectedIndex(0);

        // Réinitialiser les champs de texte avec des valeurs par défaut ou vides
        Date.setText("dd/mm/yyyy");
        Heure.setText("hh:mm");
        Duree.setText("hh:mm");
        Prix.setText("Saisir le prix");
        NbrePlace.setText("123...");
        IdPlace.setText("(Debut)..-..(Fin)");
    }//GEN-LAST:event_ReinitialiserActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetourActionPerformed

    private void GareDepartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GareDepartItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_GareDepartItemStateChanged

    private void GareDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GareDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GareDepartActionPerformed

    private void PrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrixActionPerformed

    private void NbrePlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbrePlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NbrePlaceActionPerformed

    private void IdPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPlaceActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed
    
    private void Reinitialiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reinitialiser1ActionPerformed
        // Réinitialiser tous les JComboBox à leur premier élément
        GareDepart.setSelectedIndex(0);
        GareArrivee.setSelectedIndex(0);
        TypeChaise.setSelectedIndex(0);

        // Réinitialiser les champs de texte avec des valeurs par défaut ou vides
        Date.setText("dd/mm/yyyy");
        Heure.setText("hh:mm");
        Duree.setText("hh:mm");
        Prix.setText("Saisir le prix");
        NbrePlace.setText("123...");
        IdPlace.setText("(Debut)..-..(Fin)");
    }//GEN-LAST:event_Reinitialiser1ActionPerformed

    private void Retour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Retour1ActionPerformed

    private void GareDepart1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GareDepart1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_GareDepart1ItemStateChanged

    private void GareDepart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GareDepart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GareDepart1ActionPerformed

    private void Prix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prix1ActionPerformed

    private void NbrePlace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbrePlace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NbrePlace1ActionPerformed

    private void IdPlace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPlace1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPlace1ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Reinitialiser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reinitialiser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reinitialiser2ActionPerformed

    private void Retour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Retour2ActionPerformed

    private void GareDepart2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GareDepart2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_GareDepart2ItemStateChanged

    private void GareDepart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GareDepart2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GareDepart2ActionPerformed

    private void Prix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prix2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prix2ActionPerformed

    private void NbrePlace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbrePlace2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NbrePlace2ActionPerformed

    private void IdPlace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPlace2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPlace2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        JOptionPane.showMessageDialog(this, "Votre réservation a été effectuée avec succès !");
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               CarteReduction reduction = new CarteReduction();
              reduction.setVisible(true);                                
    
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
          // Réinitialiser tous les JComboBox à leur premier élément
        GareDepart.setSelectedIndex(0);
        GareArrivee.setSelectedIndex(0);
        TypeChaise.setSelectedIndex(0);

        // Réinitialiser les champs de texte avec des valeurs par défaut ou vides
        Date.setText("dd/mm/yyyy");
        Heure.setText("hh:mm");
        Duree.setText("hh:mm");
        Prix.setText("Saisir le prix");
        NbrePlace.setText("123...");
        IdPlace.setText("(Debut)..-..(Fin)");
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add2;
    private javax.swing.JPanel Admin;
    private javax.swing.JPanel Admin1;
    private javax.swing.JPanel Admin2;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Date1;
    private javax.swing.JTextField Date2;
    private javax.swing.JTextField Duree;
    private javax.swing.JTextField Duree1;
    private javax.swing.JTextField Duree2;
    private javax.swing.JComboBox<String> GareArrivee;
    private javax.swing.JComboBox<String> GareArrivee1;
    private javax.swing.JComboBox<String> GareArrivee2;
    private javax.swing.JComboBox<String> GareDepart;
    private javax.swing.JComboBox<String> GareDepart1;
    private javax.swing.JComboBox<String> GareDepart2;
    private javax.swing.JTextField Heure;
    private javax.swing.JTextField Heure1;
    private javax.swing.JTextField Heure2;
    private javax.swing.JTextField IdPlace;
    private javax.swing.JTextField IdPlace1;
    private javax.swing.JTextField IdPlace2;
    private javax.swing.JLabel JDate;
    private javax.swing.JLabel JDate1;
    private javax.swing.JLabel JDate2;
    private javax.swing.JLabel JDuree;
    private javax.swing.JLabel JDuree1;
    private javax.swing.JLabel JDuree2;
    private javax.swing.JLabel JGareArrivee;
    private javax.swing.JLabel JGareArrivee1;
    private javax.swing.JLabel JGareArrivee2;
    private javax.swing.JLabel JGareDepart;
    private javax.swing.JLabel JGareDepart1;
    private javax.swing.JLabel JGareDepart2;
    private javax.swing.JLabel JHeure;
    private javax.swing.JLabel JHeure1;
    private javax.swing.JLabel JHeure2;
    private javax.swing.JLabel JIdPlace;
    private javax.swing.JLabel JIdPlace1;
    private javax.swing.JLabel JIdPlace2;
    private javax.swing.JLabel JNbrePlace;
    private javax.swing.JLabel JNbrePlace1;
    private javax.swing.JLabel JNbrePlace2;
    private javax.swing.JLabel JPrix;
    private javax.swing.JLabel JPrix1;
    private javax.swing.JLabel JPrix2;
    private javax.swing.JLabel JTypeChaise;
    private javax.swing.JLabel JTypeChaise1;
    private javax.swing.JLabel JTypeChaise2;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JTextField NbrePlace;
    private javax.swing.JTextField NbrePlace1;
    private javax.swing.JTextField NbrePlace2;
    private javax.swing.JTextField Prix;
    private javax.swing.JTextField Prix1;
    private javax.swing.JTextField Prix2;
    private javax.swing.JButton Reinitialiser;
    private javax.swing.JButton Reinitialiser1;
    private javax.swing.JButton Reinitialiser2;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Retour1;
    private javax.swing.JButton Retour2;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JComboBox<String> TypeChaise;
    private javax.swing.JComboBox<String> TypeChaise1;
    private javax.swing.JComboBox<String> TypeChaise2;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

} 

